### ISSUE TITLE
Update the template to capture the additional metadata required by the new format

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-template-services#100]
Update the template to capture the additional metadata required by the new format: https://github.com/EBISPOT/gwas-summary-statistics-standard

**Comment by jdhayhurst** [comment]
updates in schema v1.11

**Comment by ljwh2** [comment]
@earlEBI to test once deployed

**Comment by jdhayhurst** [comment]
make the imputation fields and case control fields mandatory if imputation or case control are true
