### ISSUE TITLE
More rigorous parameter handling

### ISSUE THREAD

**Issue by DSuveges** [EBISPOT/gwas-template-services#21]
Template generation is currently a very robust process. Incase users pass an unexpected parameter, or parameter with unexpected value, that part of the request is not considered. This might not be the best way of handling issues.

In such cases the returned response should explain the problem. It might be a returned error value. This requires changing a few functions, and change the behaviour of the endpoint.

**Comment by ljwh2** [comment]
@jdhayhurst please review as to whether we can ice this issue, I think the validation error messages are pretty informative now?

**Comment by jdhayhurst** [comment]
I don't think this ticket relevant anymore - I'll close it.
