### ISSUE TITLE
Add constraints in template so user can not add a field value longer than database expects

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/gwas-template-services#56]
As a user, I want to see an alert in the template to know that the input is too long and will eventually cause import of my submission to fail.

**Comment by jdhayhurst** [comment]
It's possible to set data validation rules on cells in the spreadsheet. I made a rule so that the values must be less than 255 chars. This works if you type a value, but it can be over-ridden by simply pasting into the cell.

**Comment by jdhayhurst** [comment]
add a note when a cell is activated explaining that the length should be below a certain length

**Comment by jdhayhurst** [comment]
deployed to sandbox

**Comment by ljwh2** [comment]
@eks-ebi please confirm this works

**Comment by eks-ebi** [comment]
Tested 2020-07-29.

When attempting to add more than 255 characters to a cell, Excel gives an error alert.

> **Alert**: Sorry, values must be less than 255 characters. Please try again.

But it seems that you can ignore this alert and save the file anyway. If you type or copy the text in and press Enter, then the alert is triggered, but if you just move away from the cell, then it won't be triggered.

I uploaded the template with >255 characters in the Reported trait field and did *not* get an error:
http://193.62.54.159/gwas/deposition/submission/5f214d6886621e0001bf6953

I think a rule for this needs to be added to the submission validation process - the alert in Excel is not enough to prevent users from submitting cells with >255 chars.
