### ISSUE TITLE
Create list of expected values for country of recruitment

### ISSUE THREAD

**Issue by tudorgroza** [EBISPOT/gwas-template-services#58]
As per https://github.com/EBISPOT/goci/issues/128 - create list of expected values for country of recruitment and add it to the METADATA schema. List of countries available here: https://www.ebi.ac.uk/gwas/docs/countries

**Comment by jdhayhurst** [comment]
added as part of PR https://github.com/EBISPOT/gwas-template-services/pull/59

**Comment by jdhayhurst** [comment]
deployed to sandbox

**Comment by twhetzel** [comment]
I uploaded a template file with a country name that did not match the expected value and an error was returned on validation.
