### ISSUE TITLE
Fix cell-level limits in Excel

### ISSUE THREAD

**Issue by tudorgroza** [EBISPOT/gwas-template-services#71]

**Comment by tudorgroza** [comment]
@ljwh2 @buniello @eks-ebi @earlEBI - apologies for the spam. Could you please give me a hand and test this. If you create a curator submission - using a curator template, the `readme` column should now have the restriction removed.

Thank you.

**Comment by earlEBI** [comment]
Tested sumstats-only and sumstats-and-metadata templates. No character limit for readme column or note column in notes tab. Looks good!
